"use client";

import Link from "next/link";
import { useLanguage } from "@/components/language-switcher";
import { Arrow, CopyCommand, Experience, FinalInvitation, Reveal } from "@/components/experience";

export function AgentPage() {
    const de = useLanguage() === "de";
    return <Experience>
        <section className="product-hero content-width"><p className="kicker">ANOMX CLI AGENT</p><h1>{de ? <>Ein Terminal.<br /><span className="gradient-text">Neue Möglichkeiten.</span></> : <>One terminal.<br /><span className="gradient-text">New possibilities.</span></>}</h1><p>{de ? "Der KI-Agent für Code, Datenanalyse und Anomalieerkennung. Untersuchen Sie Ihr System dort, wo Daten und Code bereits leben." : "The AI agent for code, data analysis, and anomaly detection. Investigate your system where the data and code already live."}</p><div className="hero-links"><a className="pill pill-primary" href="#install">{de ? "Agent installieren" : "Install the agent"}<span aria-hidden="true">↓</span></a><Link className="text-link" href="/documentation">{de ? "Dokumentation lesen" : "Read the docs"}<Arrow /></Link></div></section>
        <section className="product-section content-width" id="install"><Reveal className="product-split"><div><p className="kicker">{de ? "KLEINER ANFANG. GROSSE FRAGEN." : "SMALL START. BIG QUESTIONS."}</p><h2>{de ? <>Installieren.<br />Fragen. Verstehen.</> : <>Install.<br />Ask. Understand.</>}</h2><p>{de ? "Starten Sie Anomx in Ihrem Arbeitsverzeichnis. Verbinden Sie ein Modell und untersuchen Sie Dateien, Daten oder Code in natürlicher Sprache." : "Start Anomx in your working directory. Connect a model and investigate files, data, or code in natural language."}</p><CopyCommand command="pip install anomx" /><CopyCommand command="anomx" /><span className="install-meta">Python 3.11+ · Apache 2.0 · {de ? "API in Entwicklung" : "API in active development"}</span></div><div className="terminal-preview"><div className="terminal-title"><span className="status-dot" />anomx <span style={{marginLeft:"auto"}}>{de ? "BEISPIEL" : "EXAMPLE SESSION"}</span></div><pre><span className="cyan">$ anomx</span>{"\n\n"}<strong>Anomx.</strong>{"\n"}{de ? "Daten. Code. System Intelligence." : "Data. Code. System intelligence."}{"\n\n"}<span className="cyan">› </span>{de ? "Untersuche diese Sensordaten.\n  Was hat sich verändert?" : "Investigate these sensor readings.\n  What changed?"}{"\n\n"}{de ? "  Dateien und Datenstruktur prüfen\n  Kanäle und Muster vergleichen\n  Anomaliekandidaten erklären" : "  Inspect files and data structure\n  Compare channels and patterns\n  Explain candidate anomalies"}{"\n\n"}<span className="cyan">Ω Standard · Shift+Tab</span></pre></div></Reveal></section>
        <section className="product-section surface"><div className="content-width"><Reveal><p className="kicker">{de ? "IHR AGENT. IHR HANDLUNGSSPIELRAUM." : "YOUR AGENT. YOUR SCOPE."}</p><h2>{de ? <>Von der ersten Frage.<br /><span className="muted">Bis zur autonomen Arbeit.</span></> : <>From the first question.<br /><span className="muted">To autonomous work.</span></>}</h2><p className="section-lead">{de ? "Vier interaktive Modi. Wechseln Sie mit Shift+Tab und wählen Sie bewusst, wie viel Verantwortung Sie delegieren." : "Four interactive modes. Cycle with Shift+Tab and choose how much responsibility to delegate."}</p><div className="mode-grid">{(de ? [
            ["Plan", "Nur lesen und analysieren. Änderungen an Dateien, Prozessen oder Plattformzustand sind ausgeschlossen."],
            ["Standard", "Noch nicht freigegebene Kommandos benötigen Ihre Zustimmung. Die Voreinstellung für interaktive Arbeit."],
            ["Automatic", "Lesezugriffe und als risikoarm eingestufte Kommandos laufen automatisch. Andere Kommandos benötigen Zustimmung."],
            ["Autonomous", "Kommandos laufen ohne Freigabedialog, auch Host- und sudo-Kommandos. Für bewusst delegierte Arbeit in einer geeigneten Umgebung."]
        ] : [
            ["Plan", "Read and analyze. Operations that change files, processes, or platform state are unavailable."],
            ["Standard", "Commands that have not already been approved ask for your permission. The default for interactive work."],
            ["Automatic", "Read operations and commands classified as low risk run automatically. Other commands ask for approval."],
            ["Autonomous", "Commands run without approval prompts, including host-control and sudo commands. For deliberately delegated work in an appropriate environment."]
        ]).map(([title,body]) => <article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></Reveal></div></section>
        <section className="product-section content-width"><Reveal className="product-split"><div><p className="kicker">{de ? "LOKAL BEGINNEN. WEITERDENKEN." : "START LOCAL. THINK BEYOND."}</p><h2>{de ? <>Dort arbeiten.<br /><span className="muted">Zusammen verstehen.</span></> : <>Work right there.<br /><span className="muted">Understand together.</span></>}</h2><p>{de ? "Verbinden Sie den CLI-Agenten mit Ihrer Anomx-Plattform. Analysieren Sie am Rechner, verwalten Sie Daten und Jobs und führen Sie Erkenntnisse in einem gemeinsamen Kontext zusammen." : "Connect the CLI agent to your Anomx platform. Investigate on the machine, manage data and jobs, and bring findings into shared context."}</p><Link href="/documentation#platform" className="text-link">{de ? "Plattform verbinden" : "Connect the platform"}<Arrow /></Link></div><div className="product-list"><article><h3>{de ? "Spezialisierte Werkzeuge." : "Specialist tools."}</h3><p>{de ? "Dateien lesen, Code ausführen, Prozesse verwalten und Aufgaben an Worker-Agenten delegieren." : "Read files, run code, manage processes, and delegate focused tasks to worker agents."}</p></article><article><h3>{de ? "Kontext, der bleibt." : "Context that stays."}</h3><p>{de ? "Gespeicherte Sitzungen, lokale Erinnerungen und eigene Skills machen wiederkehrende Arbeit nachvollziehbar." : "Persisted sessions, local memories, and custom skills make recurring work inspectable."}</p></article><article><h3>{de ? "Im Hintergrund weiterdenken." : "Keep thinking in the background."}</h3><p>{de ? "Geplante Hintergrundläufe werden in der Plattform eingerichtet. Sie untersuchen Systeme innerhalb der Rechte und Budgets Ihres Teams." : "Scheduled background runs are configured in the platform. They investigate systems within your team’s permissions and budgets."}</p></article></div></Reveal></section>
        <section className="product-section surface"><div className="content-width"><Reveal><p className="kicker">{de ? "OFFEN FÜR IHRE MODELLE" : "OPEN TO YOUR MODELS"}</p><h2>{de ? <>Die Intelligenz<br /><span className="muted">Ihrer Wahl.</span></> : <>The intelligence<br /><span className="muted">you choose.</span></>}</h2><div className="provider-list"><span>OpenAI</span><span>Anthropic</span><span>Kimi</span><span>Ollama</span><span>DESY Assistant</span><span>JSC Blablador</span></div><p className="section-lead">{de ? "Verbinden Sie einen Cloud-Anbieter oder nutzen Sie ein lokal bereitgestelltes Modell über Ollama. Anbieterzugang und Modellverfügbarkeit bestimmen die nutzbaren Funktionen." : "Connect a cloud provider or use a locally served model through Ollama. Provider access and model availability determine the capabilities you can use."}</p></Reveal></div></section>
        <FinalInvitation />
    </Experience>;
}
