"use client";

import Image from "next/image";
import Link from "next/link";
import { useLanguage } from "@/components/language-switcher";
import { Arrow, Experience, FinalInvitation, Reveal } from "@/components/experience";
import { AgentFigure } from "@/components/agent-figures";
import { cases, type CaseContent } from "@/lib/cases-content";

function CaseVisual({ item, priority = false }: { item:CaseContent; priority?:boolean }) {
    const de = useLanguage() === "de";
    return item.visual === "xfel" ? <Image src="/media/xfel-intelligence.webp" width={1600} height={900} sizes="(max-width: 760px) 100vw, 1120px" priority={priority} alt={de?"KI-generierte, stilisierte Illustration eines Beschleunigertunnels, inspiriert vom European XFEL.":"AI-generated, stylized accelerator-tunnel illustration inspired by European XFEL."}/> : <div className={`case-concept-art case-concept-${item.visual}`}><AgentFigure stage={item.visual==="machine"?1:3}/></div>;
}
export function DesyLogo() { return <Image className="desy-logo" src="/images/desy-logo-white.png" alt="DESY" width={80} height={80}/>; }

export function CasesPage() {
    const language = useLanguage();
    const de = language === "de";
    return <Experience><section className="product-hero content-width"><p className="kicker">ANOMX CASES</p><h1>{de?<>Große Fragen.<br/><span className="gradient-text">Konkrete Systeme.</span></>:<>Big questions.<br/><span className="gradient-text">Real-world systems.</span></>}</h1><p>{de?"Wie System Intelligence Form annimmt. Einblicke in unsere Alpha-Arbeit und mögliche Anwendungen für Maschinen und Infrastruktur.":"Where system intelligence takes shape. Explore our alpha work and possible applications for machines and infrastructure."}</p></section>
        <section className="cases-grid content-width" aria-label={de?"Cases und Anwendungskonzepte":"Cases and application concepts"}>{cases.map(item=><Reveal key={item.slug}><Link className="case-card" href={`/cases/${item.slug}`}><div className="case-card-art"><CaseVisual item={item}/><span className="case-status">{item.kind==="alpha"?"ALPHA":de?"KONZEPT":"CONCEPT"}</span></div><div className="case-card-copy"><p className="kicker">{item[language].category}</p><h2>{item[language].name}</h2><p>{item[language].summary}</p><span className="text-link">{de?"Case entdecken":"Explore the case"}<Arrow/></span>{item.kind==="alpha"&&<DesyLogo/>}</div></Link></Reveal>)}</section><FinalInvitation/></Experience>;
}

export function CaseDetailPage({ item }: { item:CaseContent }) {
    const language = useLanguage();
    const de=language==="de";
    const copy=item[language];
    const xfel=item.kind==="alpha";
    return <Experience className="case-detail"><section className="case-detail-hero content-width"><Link href="/cases" className="case-back">← {de?"Alle Cases":"All cases"}</Link><div className="case-heading-meta"><p className="kicker">{copy.name}</p><span className="case-status">{xfel?"ALPHA":de?"ANWENDUNGSKONZEPT":"APPLICATION CONCEPT"}</span>{xfel&&<DesyLogo/>}</div><h1>{copy.title}</h1><p className="section-lead">{copy.summary}</p><figure className="case-hero-art"><CaseVisual item={item} priority/>{xfel&&<figcaption>{de?"KI-generierte Illustration, inspiriert vom European XFEL. Kein dokumentarisches Foto.":"AI-generated illustration inspired by European XFEL. Not a documentary photograph."}</figcaption>}</figure></section>
        <section className="case-editorial content-width"><div className="case-editorial-label"><p className="kicker">{de?"DER KONTEXT":"THE CONTEXT"}</p>{xfel&&<p className="alpha-note">{de?"Alpha in Entwicklung. Noch nicht im operativen Einsatz. Der DAQ-Start ist als nächster Schritt geplant.":"Alpha in development. Not in operational use. DAQ rollout is planned as the next step."}</p>}</div><div><Reveal><h2>{de?"Mehr als einzelne Signale.":"More than individual signals."}</h2><p>{copy.challenge}</p></Reveal><Reveal><h2>{de?"Ein Systembild, das mitlernt.":"A system map that keeps learning."}</h2><p>{copy.approach}</p></Reveal></div></section>
        {xfel&&<section className="case-discovery-section surface"><div className="content-width"><Reveal className="product-split"><div><p className="kicker">AUTONOMOUS DISCOVERY</p><h2>{de?<>Aus Kennungen<br/><span className="muted">wird Zusammenhang.</span></>:<>From identifiers<br/><span className="muted">to understanding.</span></>}</h2><p className="section-lead">{de?"Einzelne Property-Beschreibungen werden zu möglichen Beziehungen. Aus Beziehungen entsteht eine Hierarchie: von der Anlage über Subsysteme bis zum Signal.":"Individual property descriptions become candidate relationships. Relationships form a hierarchy: from the facility, through its subsystems, down to the signal."}</p></div><div className="discovery-map"><code>FACILITY / DEVICE / LOCATION / PROPERTY</code><span className="discovery-down" aria-hidden="true">↓</span><div className="discovery-core">Anomx Background Agent</div><span className="discovery-down" aria-hidden="true">↓</span><div className="discovery-root">{de?"Beschleuniger":"Accelerator"}</div><div className="discovery-branches"><span>{de?"HF-System":"RF system"}</span><span>{de?"Kühlung":"Cooling"}</span><span>{de?"Vakuum":"Vacuum"}</span></div><p>{de?"Schematische, abgeleitete Zuordnung — prüfbar und korrigierbar.":"Illustrative inferred mapping — inspectable and correctable."}</p></div></Reveal><div className="case-scale"><div><strong>100M+</strong><span>{de?"Properties als Planungsgröße":"Properties as a planning scale"}</span></div><p>{de?"Die projektseitige Größenordnung für den zu erschließenden Property-Raum. Discovery und gezielte Datenaufnahme werden getrennt skaliert. Die Zahl ist kein gemessener Durchsatz und keine Anzahl gleichzeitig abonnierter Kanäle.":"The project’s planning estimate for the property space to explore. Discovery and selective acquisition scale separately. This is not a measured throughput or a count of simultaneously subscribed channels."}</p></div></div></section>}
        <section className="case-steps content-width"><Reveal><p className="kicker">{de?"DER WEG ZUR SYSTEM INTELLIGENCE":"THE PATH TO SYSTEM INTELLIGENCE"}</p><h2>{de?"Schritt für Schritt verbunden.":"Connected. Step by step."}</h2></Reveal><div>{copy.steps.map(([title,body],i)=><Reveal key={title} className="case-step"><span>0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div>{xfel&&<span className="case-step-phase">{i<2?(de?"Alpha-Arbeit":"Alpha work"):(de?"Nächste Schritte":"Next steps")}</span>}</Reveal>)}</div></section>
        {xfel&&<section className="case-editorial content-width case-sources"><p className="kicker">{de?"TECHNISCHER HINTERGRUND":"TECHNICAL CONTEXT"}</p><div><p>{de?"DOOCS bietet ZeroMQ-basierte Kommunikation und unterstützt auch RPC. Anomx baut darauf mit dedizierten Workern auf. Das Ziel: effiziente, gezielte Erfassung und eine nachvollziehbare Verbindung zwischen Daten, Modellen und physischem System.":"DOOCS provides ZeroMQ-based communication and also supports RPC. Anomx builds on this with dedicated workers. The goal is efficient, selective acquisition and a traceable connection between data, models and the physical system."}</p><div className="case-source-links"><a href="https://doocs.desy.de/" target="_blank" rel="noreferrer">DOOCS <Arrow diagonal/></a><a href="https://xfel.desy.de/" target="_blank" rel="noreferrer">{de?"Der XFEL-Beschleuniger bei DESY":"The XFEL accelerator at DESY"}<Arrow diagonal/></a></div><p className="architecture-note">{de?"Forschungs- und Entwicklungsarbeit im Alpha-Stadium. Diese Darstellung beschreibt den Aufbau der Anomx-Integration und keine produktiv eingesetzte Lösung oder offizielle Produktempfehlung von DESY oder European XFEL.":"Alpha-stage research and development. This case describes the Anomx integration being built, not a production deployment or an official product endorsement by DESY or European XFEL."}</p></div></section>}
        <section className="case-next content-width"><Link className="text-link" href="/technology">{de?"Die Architektur dahinter":"Explore the architecture"}<Arrow/></Link><Link className="text-link" href="/cases">{de?"Alle Cases ansehen":"See all cases"}<Arrow/></Link></section><FinalInvitation/>
    </Experience>;
}
