"use client";

import Link from "next/link";
import Image from "next/image";
import { useLanguage } from "@/components/language-switcher";
import { Arrow, Experience, FinalInvitation, Reveal } from "@/components/experience";
import { BackgroundStory, ScienceSection } from "@/components/intelligence-demo";

export function PlatformPage() {
    const de = useLanguage() === "de";
    return <Experience>
        <section className="product-hero content-width"><p className="kicker">ANOMX PLATFORM</p><h1>{de ? <>Vom laufenden System.<br /><span className="gradient-text">Zum denkenden System.</span></> : <>From running systems.<br /><span className="gradient-text">To reasoning systems.</span></>}</h1><p>{de ? "Eine KI-Schicht über Ihren Daten, Modellen und Maschinen. Anomx verbindet kontinuierliche Analyse mit einem Agenten, der Veränderungen untersucht und die nächsten Schritte vorbereitet." : "An AI layer above your data, models, and machines. Anomx connects continuous analysis with an agent that investigates change and prepares what comes next."}</p><div className="hero-links"><Link href="/early-access" className="pill pill-primary">{de ? "Early Access anfragen" : "Request early access"}<Arrow /></Link><a href="#platform-foundation" className="text-link">{de ? "So funktioniert es" : "See how it works"}<span aria-hidden="true">↓</span></a></div></section>
        <section className="product-section content-width" id="platform-foundation"><Reveal className="product-split"><div><p className="kicker">{de ? "ALLES HÄNGT ZUSAMMEN" : "EVERYTHING IS CONNECTED"}</p><h2>{de ? <>Komplexe Welt.<br /><span className="muted">Gemeinsamer Kontext.</span></> : <>A complex world.<br /><span className="muted">A shared context.</span></>}</h2><p>{de ? "Verbinden Sie Daten mit den Systemen, aus denen sie entstehen. Kanäle, Datasets, Analysejobs und Findings werden gemeinsam mit Ihrer Infrastruktur verständlich und nachvollziehbar." : "Connect data to the systems that produce it. Channels, datasets, analysis jobs, and findings become understandable and traceable alongside your infrastructure."}</p></div><div className="system-map" aria-label={de ? "Architektur der Anomx-Plattform" : "Anomx platform architecture"}><div className="system-map-row"><span>{de ? "Maschinen" : "Machines"}</span><span>{de ? "Sensoren" : "Sensors"}</span><span>{de ? "Infrastruktur" : "Infrastructure"}</span></div><div className="system-map-connector" aria-hidden="true">↕</div><div className="system-map-core"><strong>Anomx Intelligence</strong><small>{de ? "Daten · Modelle · Hintergrundagent" : "Data · Models · Background agent"}</small></div><div className="system-map-connector" aria-hidden="true">↕</div><div className="system-map-row"><span>{de ? "Erkenntnisse" : "Findings"}</span><span>{de ? "Empfehlungen" : "Recommendations"}</span><span>{de ? "Aktionen" : "Actions"}</span></div></div></Reveal></section>
        <section className="product-capture-section content-width"><Reveal><div className="section-intro"><p className="kicker">{de ? "IN DER PLATTFORM" : "INSIDE THE PLATFORM"}</p><h2>{de ? <>Ein Auftrag.<br /><span className="muted">Fortlaufendes Verständnis.</span></> : <>One instruction.<br /><span className="muted">Ongoing understanding.</span></>}</h2><p className="section-lead">{de ? "Ein Data-Discovery-Agent erkundet regelmäßig Datenkanäle und ordnet sie den passenden Systemen zu. Jeder Durchlauf baut auf dem bisherigen Kontext auf." : "A data-discovery agent regularly explores channels and connects them to the systems they belong to. Each run builds on the context that came before."}</p></div><figure className="platform-artwork"><Image src="/media/platform-intelligence.webp" width={1920} height={1080} sizes="(max-width: 760px) 100vw, 1120px" alt={de ? "Abstrakte Glasstruktur: Datenströme verdichten sich zu verbundenem Systemwissen." : "Abstract glass sculpture: data streams converge into connected system knowledge."} /><figcaption>{de ? "Aus verbundenen Daten entsteht fortlaufender Kontext." : "Connected data becomes continuous context."}</figcaption></figure></Reveal></section>
        <BackgroundStory compact />
        <section className="technology-teaser content-width"><Reveal><p className="kicker">UNDER THE SURFACE</p><h2>{de ? "Intelligenz hat eine Architektur." : "Intelligence has an architecture."}</h2><Link href="/technology" className="text-link">{de ? "Schicht für Schicht entdecken" : "Explore it layer by layer"}<Arrow /></Link></Reveal></section>
        <section className="product-section content-width"><Reveal className="product-split"><div><p className="kicker">{de ? "BEREIT FÜR ECHTE SYSTEME" : "BUILT AROUND REAL SYSTEMS"}</p><h2>{de ? <>Autonomie ermöglichen.<br /><span className="muted">Kontrolle behalten.</span></> : <>Enable autonomy.<br /><span className="muted">Keep control.</span></>}</h2><p>{de ? "Ob Forschungsanlage, industrielle Maschine oder verteilte Infrastruktur: Anomx bringt KI dorthin, wo Entscheidungen zählen." : "From research facilities to industrial machines and distributed infrastructure, Anomx brings AI to the places where decisions matter."}</p></div><div className="product-list">{(de ? [
            ["Ein klarer Handlungsspielraum.", "Das Team legt fest, welche Plattformobjekte der Hintergrundagent erstellen, ändern oder löschen darf. Alles Weitere wird zur Empfehlung."],
            ["Ressourcen mit Grenzen.", "Stündliche und tägliche Tokenbudgets steuern die Hintergrundarbeit. Erreichte Limits pausieren die Ausführung."],
            ["Entscheidungen mit Verlauf.", "Nachvollziehbare Durchläufe, Belege, Objektversionen und menschliches Feedback halten das System überprüfbar."],
            ["Compute dort, wo es gebraucht wird.", "Verteilte Worker übernehmen Datenerfassung und CPU- oder GPU-Workloads. Die Plattform hält Ausführung und Kontext zusammen."]
        ] : [
            ["A defined scope of action.", "Your team chooses which platform objects background agents may create, update, or delete. Other changes become recommendations."],
            ["Resources with boundaries.", "Hourly and daily token budgets govern background work. Reaching a limit pauses execution."],
            ["Decisions with a history.", "Inspectable runs, evidence, object versions, and human feedback keep the system accountable."],
            ["Compute where it’s needed.", "Distributed workers handle data acquisition and CPU or GPU workloads. The platform connects execution with context."]
        ]).map(([title, body]) => <article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></Reveal></section>
        <ScienceSection />
        <FinalInvitation />
    </Experience>;
}
